// Dati e contatti degli operatori di PRISMA.
// Questo file viene caricato prima di app.js.
window.OPERATOR_CONTACTS = {
  arcadiatour: {
    name: "Arcadia Tour",
    email: "booking2@arcadiaviaggi.it",
    phone: "",
    role: "",
    notes: "",
    contactName: "Domenico",
    emails: [],
  },
  booking: {
    name: "Booking.com",
    email: "giorgia.bartolomei@booking.com",
    phone: "",
    role: "",
    notes: "",
    contactName: "Giorgia Bartolomei",
    emails: [],
  },
  expedia: {
    name: "Expedia",
    email: "fmonaco@expediagroup.com",
    phone: "",
    role: "Francesca Monaco",
    notes: "",
    emails: [],
  },
  webbeds: {
    name: "WebBeds",
    email: "Andrea.Giuncato@webbeds.com",
    phone: "",
    role: "Andrea Giuncato",
    notes: "",
    emails: [],
  },
  serhs: {
    name: "WelcomeBeds (Serhs)",
    email: "nuria.consul@welcomebeds.com",
    phone: "",
    role: "Nuria Consul Garcia",
    notes: "",
    emails: [],
  },
  hotelbeds: {
    name: "HotelBeds (HBX Group)",
    email: "a.menegaz@hbxgroup.com",
    phone: "",
    role: "Andrea Menegaz",
    notes: "",
    emails: [],
  },
  agoda: {
    name: "Agoda",
    email: "Luca.Bigini@agoda.com",
    phone: "",
    role: "Luca Bigini",
    notes: "",
    emails: [],
  },
  edreams: {
    name: "eDreams",
    email: "sonia.zollet@edreamsodigeo.com",
    phone: "",
    role: "Sonia Zollet",
    notes: "",
    emails: [],
  },
  lastminute: {
    name: "Lastminute.com",
    email: "monica.metalli@lastminute.com",
    phone: "",
    role: "Monica Metalli",
    notes: "",
    emails: [],
  },
  italcamel: {
    name: "Italcamel",
    email: "valentina.ciavattone@italcamel.com",
    phone: "",
    role: "Valentina Ciavattone",
    notes: "",
    emails: [],
  },
  hyperguest: {
    name: "HyperGuest",
    email: "silvia.dagradi@hyperguest.com",
    phone: "",
    role: "Silvia Dagradi",
    notes: "",
    emails: [],
  },
  keytel: {
    name: "Keytel",
    email: "ludemi.arnillas@keytel.com",
    phone: "",
    role: "Ludemi Arnillas",
    notes: "",
    emails: [],
  },
  easyconsulting: {
    name: "EasyConsulting",
    email: "matteo.gentile@easyconsulting.com",
    phone: "",
    role: "Matteo Gentile",
    notes: "",
    emails: [],
  },
  destinationitalia: {
    name: "Destination Italia",
    email: "simone.pasquazi@destinationitalia.com",
    phone: "",
    role: "Simone Pasquazi",
    notes: "",
    emails: [],
  },
  cisalpina: {
    name: "Cisalpina Tours",
    email: "cisahotelweb@cisalpinatours.it",
    phone: "",
    role: "Giorgia Dell'Aquila",
    notes: "",
    emails: [],
  },
  tripcom: {
    name: "Trip.com",
    email: "francesca.marinotti@trip.com",
    phone: "",
    role: "Francesca Marinotti",
    notes: "",
    emails: [],
  },
  traveltino: {
    name: "Traveltino",
    email: "christian.bovecchi@grupoveci.es",
    phone: "",
    role: "Christian Bovecchi",
    notes: "",
    emails: [],
  },
  xenia: {
    name: "Xenia",
    email: "sharon.disciullo@xeniahs.com",
    phone: "",
    role: "Sharon Di Sciullo",
    notes: "",
    emails: [],
  },
  g2travel: {
    name: "G2 Travel",
    email: "davide.cevoli@g2-travel.com",
    phone: "",
    role: "Davide Cevoli",
    notes: "",
    emails: [],
  },
};
